In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [6]:
# get dimension

b.ndim

2

In [7]:

b.shape

(2, 6)

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('int64')